#!/bin/sh

set -x

icon="-*-siji-*"
height="16"


get_window() {
    # Get title of focused window.
    printf "%.8s\\n" "$(xdotool getwindowfocus getwindowname)"
}


get_date() {
    # Get the date and time.
    printf "%s\\n" "$(date +"%a %d %b - %l:%M %p")"
}


get_volume() {
    # Get the system volume.
    volume="$(amixer sget Master | grep -o -m 1 -E "[[:digit:]]+%")"

    case "$volume" in
        0%|[0-9]%)   vol_icon=" " ;;
        1?%|2?%|3?%) vol_icon="" ;;
        4?%|5?%|6?%) vol_icon="" ;;
        *) vol_icon="" ;;
    esac

    printf "%s\\n" "$(icon "$vol_icon") ${volume}"

}


icon() {
    # Format an icon.
    printf "%s\\n" "%{F #ff00ff}${1}%{F}"
}


main() {

    # Loop and print the info.
    while :; do
        window="$(icon "\ue2ff") $(get_window)"
        date="$(get_date)"
        volume="$(get_volume)"

        printf "%s%s%s\\n" \
               "%{l}    ${window}" \
               "%{c}${date}" \
               "%{r} ${volume}    "
        sleep 1
    done |\

    # Launch lemonbar.
    lemonbar -g "x$height" \
             -B "#f9f9f9" -F "#2d2d2d"\
             -f "$icon"
}


main "$@"
